"""
backend/app/services/vector_store_service.py

Service for managing vector storage and semantic search using ChromaDB.

==============================================================================
WHAT IS A VECTOR DATABASE & COLLECTION? (FOR BEGINNERS)
==============================================================================
In traditional databases (like SQL or MongoDB), you search for exact words or numbers 
(e.g., SELECT * FROM feedback WHERE text = "slow checkout").

A VECTOR DATABASE (like ChromaDB) stores text alongside its numerical "embedding vector".
Instead of exact keyword matching, a vector database lets us perform "SEMANTIC SEARCH" —
finding documents that share similar meaning, even if they use completely different words!

What is a COLLECTION?
Think of a COLLECTION like a table in a relational database, or a dedicated folder 
of documents. Each item stored inside a collection contains four key parts:
1. ID: A unique identifier for the feedback item.
2. Document: The raw text (e.g., "The checkout page is very slow on mobile").
3. Embedding: The list of numbers representing the text's semantic meaning.
4. Metadata: Extra tags attached to the text (e.g., theme_name, sentiment, intent, urgency).
==============================================================================
"""

import os
from pathlib import Path
import chromadb

# ==============================================================================
# Step 1: Initialize Persistent ChromaDB Client & Collection
# ==============================================================================
# Resolve exact path to backend/chroma_data folder regardless of working directory
BACKEND_DIR = Path(__file__).resolve().parent.parent.parent
CHROMA_DATA_DIR = BACKEND_DIR / "chroma_data"

# Create a persistent ChromaDB client that saves database data to backend/chroma_data
client = chromadb.PersistentClient(path=str(CHROMA_DATA_DIR))

# Get or create the "feedback_memory" collection
# This collection acts as long-term memory for storing customer feedback vectors
collection = client.get_or_create_collection(name="feedback_memory")


# ==============================================================================
# Step 2: Store Feedback Item Function
# ==============================================================================
def store_feedback_item(
    item_id: str,
    text: str,
    embedding: list[float],
    theme_name: str,
    sentiment: str,
    intent: str,
    urgency: str
) -> None:
    """
    Stores a single feedback item into the ChromaDB 'feedback_memory' collection.

    What this function does:
    1. Takes the item's unique ID, text, embedding vector, and categorizations.
    2. Packages metadata into a dictionary.
    3. Saves the document, vector, and metadata into ChromaDB persistent storage.

    Args:
        item_id (str): Unique identifier for this feedback item.
        text (str): Raw text content of the feedback.
        embedding (list[float]): Numerical embedding vector generated by Gemini.
        theme_name (str): Thematic cluster name (e.g., "Performance").
        sentiment (str): Sentiment tag ("Positive", "Negative", or "Neutral").
        intent (str): Feedback type ("Bug", "Feature Request", or "UX Friction").
        urgency (str): Urgency rating ("Low", "Medium", or "High").

    Raises:
        ValueError: If input validation fails or ChromaDB insertion encounters an error.
    """
    if not item_id or not text or not embedding:
        raise ValueError("item_id, text, and embedding are required to store feedback.")

    try:
        # Save to ChromaDB collection
        collection.add(
            ids=[item_id],
            embeddings=[embedding],
            documents=[text],
            metadatas=[{
                "theme_name": theme_name,
                "sentiment": sentiment,
                "intent": intent,
                "urgency": urgency
            }]
        )
    except Exception as e:
        raise ValueError(f"Failed to store feedback item in ChromaDB: {str(e)}")


# ==============================================================================
# Step 3: Find Similar Feedback Function
# ==============================================================================
def find_similar_feedback(embedding: list[float], top_k: int = 3) -> list[dict]:
    """
    Performs a semantic similarity search in ChromaDB using a query embedding vector.

    What this function does:
    1. Checks how many items currently exist in the 'feedback_memory' collection.
    2. Gracefully returns an empty list if the database has no records yet.
    3. Queries ChromaDB for the closest vector matches up to top_k results.
    4. Returns a list of dictionaries containing matched text, metadata, and distance scores.

    Args:
        embedding (list[float]): Query embedding vector to compare against database.
        top_k (int): Maximum number of similar items to retrieve (default: 3).

    Returns:
        list[dict]: List of matched records formatted as:
            [
                {
                    "id": "item_123",
                    "document": "The checkout page is slow",
                    "metadata": {"theme_name": "Performance", ...},
                    "distance": 0.123
                },
                ...
            ]

    Raises:
        ValueError: If querying ChromaDB fails.
    """
    if not embedding:
        raise ValueError("Query embedding vector must not be empty.")

    try:
        # Check current item count in the collection to handle empty state gracefully
        item_count = collection.count()
        if item_count == 0:
            return []

        # Determine effective number of results to request (cannot exceed available items)
        effective_k = min(top_k, item_count)

        # Query ChromaDB collection with the query embedding
        results = collection.query(
            query_embeddings=[embedding],
            n_results=effective_k
        )

        similar_items = []
        if results and results.get("documents") and len(results["documents"]) > 0:
            docs = results["documents"][0]
            metas = results["metadatas"][0] if results.get("metadatas") else [{}] * len(docs)
            dists = results["distances"][0] if results.get("distances") else [0.0] * len(docs)
            ids = results["ids"][0] if results.get("ids") else [""] * len(docs)

            for doc, meta, dist, item_id in zip(docs, metas, dists, ids):
                similar_items.append({
                    "id": item_id,
                    "document": doc,
                    "metadata": meta,
                    "distance": dist
                })

        return similar_items

    except Exception as e:
        raise ValueError(f"Failed to query similar feedback from ChromaDB: {str(e)}")
